/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package poselcm;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class pose_list_t implements lcm.lcm.LCMEncodable
{
    public long timestamp;
    public int n;
    public poselcm.pose_t poses[];
 
    public pose_list_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x09309d316bc1b349L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(poselcm.pose_list_t.class))
            return 0L;
 
        classes.add(poselcm.pose_list_t.class);
        long hash = LCM_FINGERPRINT_BASE
             + poselcm.pose_t._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.timestamp); 
 
        outs.writeInt(this.n); 
 
        for (int a = 0; a < this.n; a++) {
            this.poses[a]._encodeRecursive(outs); 
        }
 
    }
 
    public pose_list_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public pose_list_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static poselcm.pose_list_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        poselcm.pose_list_t o = new poselcm.pose_list_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.timestamp = ins.readLong();
 
        this.n = ins.readInt();
 
        this.poses = new poselcm.pose_t[(int) n];
        for (int a = 0; a < this.n; a++) {
            this.poses[a] = poselcm.pose_t._decodeRecursiveFactory(ins);
        }
 
    }
 
    public poselcm.pose_list_t copy()
    {
        poselcm.pose_list_t outobj = new poselcm.pose_list_t();
        outobj.timestamp = this.timestamp;
 
        outobj.n = this.n;
 
        outobj.poses = new poselcm.pose_t[(int) n];
        for (int a = 0; a < this.n; a++) {
            outobj.poses[a] = this.poses[a].copy();
        }
 
        return outobj;
    }
 
}

